os:
    - linux
    - osx

services:
  -docker
  
cache:
    directories:
        - precompiled
        - html
        - highlights/node_modules
        - $HOME/.rakudobrew
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - graphviz
      - g++-4.8
      - ruby-sass

fast_finish: true

branches:
  except:
    - gh-pages

notifications:
  irc:
    channels:
    - "irc.freenode.net#perl6"
    on_success: change
    on_failure: always
    template:
      - "Doc build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"

before_install:
  - nvm install 7.2.1
  - nvm use 7.2.1

install:
  - utils/travis-build.sh

script:
  - export CXX=$(command -v g++-4.8 >/dev/null 2>&1; if [ $? -eq 1 ]; then printf "g++"; else printf "g++-4.8"; fi)
  - $CXX --version
  - utils/travis-test.sh

matrix:
matrix:
    include:
        - env: BUILDENV=whateverable
        - env: BUILDENV=docker
