os:
    - linux
cache:
    directories:
        - precompiled
        - html
        - highlights/node_modules
        - $HOME/.rakudobrew
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - graphviz
      - g++-4.8
      - ruby-sass

fast_finish: true

branches:
  except:
    - gh-pages

before_install:
  - nvm install 7.2.1
  - nvm use 7.2.1
 
install:
  - wget https://whateverable.6lang.org/HEAD.tar.gz
  - tar -xv --absolute-names -f HEAD.tar.gz
  - HEAD_BUILD="$(echo /tmp/whateverable/rakudo-moar/*/bin)"
  - export PATH="$PATH:$HEAD_BUILD"
  - ZEF_BUILD="$(dirname $HEAD_BUILD)/share/perl6/site/bin"
  - git clone https://github.com/ugexe/zef.git && cd zef && perl6 -Ilib bin/zef install . && cd ..
  - export PATH="$PATH:$ZEF_BUILD"
  - travis_retry zef --/tap-harness --force --/test install LWP::Simple
  - travis_retry zef --/tap-harness --depsonly install .

script:
  - make test
  - export CXX=$(command -v g++-4.8 >/dev/null 2>&1; if [ $? -eq 1 ]; then printf "g++"; else printf "g++-4.8"; fi)
  - $CXX --version
  - make html-nohighlight
#  - make html
matrix:
  allow_failures:
    - os: osx
