os:
    - linux
cache:
    directories:
        - precompiled
        - html
        - highlights/node_modules
        - $HOME/.rakudobrew
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - graphviz
      - g++-4.8
      - ruby-sass
      
services:
  - docker

fast_finish: true

branches:
  except:
    - gh-pages

before_install:
  - nvm install 7.2.1
  - nvm use 7.2.1

install:
  - docker pull jjmerelo/perl6-doccer

script:
  - docker run -t -v $TRAVIS_BUILD_DIR:/test jjmerelo/perl6-doccer
  - export CXX=$(command -v g++-4.8 >/dev/null 2>&1; if [ $? -eq 1 ]; then printf "g++"; else printf "g++-4.8"; fi)
  - $CXX --version
  - make html-nohighlight

matrix:
  allow_failures:
    - os: osx
