version: 2
jobs:
  test-linux:
    docker:
      - image: jjmerelo/test-perl6
    steps:
      - checkout
      - run:
          name: Test documentable
          command: |
            zef install Documentable
            # test one build
            documentable start -a -v 

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-linux
