version: 2
jobs:
  test-linux:
    steps:
      - checkout
      - run:
          name: Test documentable
          command: |
            zef install Documentable
            # test one build
            git clone https://github.com/perl6/doc
            cd doc
            documentable start -a -v 

workflows:
  version: 2
  test-deploy:
    jobs:
      - test-linux
