name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./util/github-action-test.sh t
        env:
          TEST_IMAGE: docker.io/jjmerelo/perl6-doccer:latest
